---
all:
  hosts:
    abreina:
      ansible_host: 46.245.69.216
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/openstacktasks/id_ed25519
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
