all:
  hosts:
    artifact:
      ansible_host: 10.20.0.40
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@46.245.69.222'

  vars:
    ansible_ssh_private_key_file: ~/openstacktasks/id_ed25519
