---
all:
  hosts:
    almalinux-test:
      ansible_host: "{{ almalinux_ip }}"
      ansible_user: almalinux
      ansible_ssh_private_key_file: "{{ ssh_key_path | default('~/.ssh/alma_key') }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ProxyJump=xadmin@172.40.30.21"
